##################################################
# Variables
#
rust_env := "rustup show"
rust_edition := "2021"
open := if os() == "linux" {
  "xdg-open"
} else if os() == "macos" {
  "open"
} else {
  "start \"\" /max"
}

app_name := "rust_mystery"
version := "v1_0_0"
project_directory := justfile_directory()
release := `git describe --abbrev=0 --always`
url := "https://gitlab.hevs.ch/course/car/car-labs"

##################################################
# COMMANDS
#

# List all commands
default:
  just --list

# Information about the environment
@info:
  echo "Environment Informations\n------------------------\n"
  echo "OS   : {{os()}}({{arch()}})"
  echo "Open : {{open}}"
  echo "Rust :"
  echo "`{{rust_env}}`"

# Install dependencies
[macos]
install:
  curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
  cargo install --locked trunk
  brew install mingw-w64
  brew install hyperfine

# Install dependencies
[windows]
[linux]
install:
  curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
  cargo install --locked trunk

# release the app for mac aarch64
release-mac-aarch64:
  rustup target add aarch64-apple-darwin
  cargo build -r --target=aarch64-apple-darwin
  mkdir -p release/ && cp "build/aarch64-apple-darwin/release/{{app_name}}" "release/{{app_name}}_{{version}}_Mac_AARCH64"

# release the app for linux x64
[windows]
release-linux-x64:
  rustup target add x86_64-unknown-linux-musl
  cargo build -r --target=x86_64-unknown-linux-musl
  xcopy /v /f /y "uild\x86_64-unknown-linux-musl\release\{{app_name}}" "release\{{app_name}}_{{version}}_Linux_x64"

# release the app for linux x64
[macos]
[linux]
release-linux-x64:
  rustup target add x86_64-unknown-linux-musl
  cargo build -r --target=x86_64-unknown-linux-musl
  mkdir -p release/ && cp -f -v build/x86_64-unknown-linux-musl/release/{{app_name}} release/{{app_name}}_{{version}}_Linux_x64

# release the app for win x64
[windows]
release-win-x64:
  rustup target add x86_64-pc-windows-msvc
  cargo build -r --target=x86_64-pc-windows-msvc
  xcopy /v /f /y build\x86_64-pc-windows-msvc\release\{{app_name}} release\{{app_name}}_{{version}}_Windows_x64.exe

# release the app for windows x64
[macos]
[linux]
release-win-x64:
  rustup target add x86_64-pc-windows-gnu
  cargo build -r --target=x86_64-pc-windows-gnu

  mkdir -p release/ && cp -f -v build/x86_64-pc-windows-gnu/release/{{app_name}}.exe release/{{app_name}}_{{version}}_Windows_x64.exe

# create for all platforms a binary
release-all:
  just release-linux-x64
  just release-mac-aarch64
  just release-win-x64

# build and run the mystery program with hyperfine in release mode (default -m 1)
[unix]
build-run-mystery mystery="1" args="":
  cargo build --release
  hyperfine --warmup 3 --export-markdown mystery-{{mystery}}.md --show-output --min-runs 10 "build/release/rust_mystery -m {{mystery}} {{args}}"

# build and run the mystery program with hyperfine in release mode (default -m 1)
[windows]
build-run-mystery mystery="1" args="":
  cargo build --release
  hyperfine --warmup 3 --export-markdown mystery-{{mystery}}.md --show-output --min-runs 10 "target\release\rust_mystery.exe -m {{mystery}} {{args}}"

# build and run alls mystery programs (-m [1..=4]) with hyperfine in release mode
[unix]
build-run-mysteries args="":
  cargo build --release
  hyperfine --warmup 3 --export-markdown mysteries.md --show-output --min-runs 10 "build/release/rust_mystery -m 1 {{args}}" "build/release/rust_mystery -m 2 {{args}}" "build/release/rust_mystery -m 3 {{args}}" "build/release/rust_mystery -m 4 {{args}}" "build/release/rust_mystery -m 5 {{args}}"

# build and run alls mystery programs (-m [1..=4]) with hyperfine in release mode
[windows]
build-run-mysteries args="":
  cargo build --release
  hyperfine --warmup 3 --export-markdown mysteries.md --show-output --min-runs 10 "target\release\rust_mystery.exe -m 1 {{args}}" "target\release\rust_mystery.exe -m 2 {{args}}" "target\release\rust_mystery.exe -m 3 {{args}}" "target\release\rust_mystery.exe -m 4 {{args}}" "target\release\rust_mystery.exe -m 5 {{args}}"

# build and run alls mystery programs (-m [1..=4]) with hyperfine in release mode
[unix]
build-run-mysteries-solutions:
  cargo build --release
  hyperfine --warmup 3 --export-markdown mysteries.md --show-output --min-runs 10 "build/release/rust_mystery -m 1 -v" "build/release/rust_mystery -m 2 -v" "build/release/rust_mystery -m 3 -v" "build/release/rust_mystery -m 4 -v" "build/release/rust_mystery -m 5 -v"

# build and run alls mystery programs (-m [1..=4]) with hyperfine in release mode
[windows]
build-run-mysteries-solutions:
  cargo build --release
  hyperfine --warmup 3 --export-markdown mysteries.md --show-output --min-runs 10 "target\release\rust_mystery.exe -m 1 -v" "target\release\rust_mystery.exe -m 2 -v" "target\release\rust_mystery.exe -m 3 -v" "target\release\rust_mystery.exe -m 4 -v" "target\release\rust_mystery.exe -m 5 -v"

# run the mystery program with hyperfine (default -m 1)
[macos]
run-mystery mystery="1" args="":
  hyperfine --warmup 3 --export-markdown mystery-{{mystery}}.md --show-output --min-runs 10 "release/rust_mystery_{{version}}_Mac_AARCH64 -m {{mystery}} {{args}}"

[linux]
run-mystery mystery="1" args="":
  hyperfine --warmup 3 --export-markdown mystery-{{mystery}}.md --show-output --min-runs 10 "release/rust_mystery_{{version}}_Linux_x64 -m {{mystery}} {{args}}"

[windows]
run-mystery mystery="1" args="":
  hyperfine --warmup 3 --export-markdown mystery-{{mystery}}.md --show-output --min-runs 10 "release\rust_mystery_{{version}}_Windows_x64.exe -m {{mystery}} {{args}}"

# runs all mystery programs (-m [1..=4]) with hyperfine in release mode
[macos]
run-mysteries args="":
  hyperfine --warmup 3 --export-markdown mysteries.md --show-output --min-runs 10 "release/rust_mystery_{{version}}_Mac_AARCH64 -m 1 {{args}}" "release/rust_mystery_{{version}}_Mac_AARCH64 -m 2 {{args}}" "release/rust_mystery_{{version}}_Mac_AARCH64 -m 3 {{args}}" "release/rust_mystery_{{version}}_Mac_AARCH64 -m 4 {{args}}" "release/rust_mystery_{{version}}_Mac_AARCH64 -m 5 {{args}}"

[linux]
run-mysteries args="":
  hyperfine --warmup 3 --export-markdown mysteries.md --show-output --min-runs 10 "release/rust_mystery_{{version}}_Linux_x64 -m 1 {{args}}" "release/rust_mystery_{{version}}_Linux_x64 -m 2 {{args}}" "release/rust_mystery_{{version}}_Linux_x64 -m 3 {{args}}" "release/rust_mystery_{{version}}_Linux_x64 -m 4 {{args}}" "release/rust_mystery_{{version}}_Linux_x64 -m 5 {{args}}"

[windows]
run-mysteries args="":
  hyperfine --warmup 3 --export-markdown mysteries.md --show-output --min-runs 10 "release\rust_mystery_{{version}}_Windows_x64.exe -m 1 {{args}}" "release\rust_mystery_{{version}}_Windows_x64.exe -m 2 {{args}}" "release\rust_mystery_{{version}}_Windows_x64.exe -m 3 {{args}}" "release\rust_mystery_{{version}}_Windows_x64.exe -m 4 {{args}}" "release\rust_mystery_{{version}}_Windows_x64.exe -m 5 {{args}}"

# runs all mystery programs (-m [1..=4]) with hyperfine in release mode
[macos]
run-mysteries-solutions:
  hyperfine --warmup 3 --export-markdown mysteries.md --show-output --min-runs 10 "release/rust_mystery_{{version}}_Mac_AARCH64 -m 1 -v" "release/rust_mystery_{{version}}_Mac_AARCH64 -m 2 -v" "release/rust_mystery_{{version}}_Mac_AARCH64 -m 3 -v" "release/rust_mystery_{{version}}_Mac_AARCH64 -m 4 -v" "release/rust_mystery_{{version}}_Mac_AARCH64 -m 5 -v"

[linux]
run-mysteries-solutions:
  hyperfine --warmup 3 --export-markdown mysteries.md --show-output --min-runs 10 "release/rust_mystery_{{version}}_Linux_x64 -m 1 -v" "release/rust_mystery_{{version}}_Linux_x64 -m 2 -v" "release/rust_mystery_{{version}}_Linux_x64 -m 3 -v" "release/rust_mystery_{{version}}_Linux_x64 -m 4 -v" "release/rust_mystery_{{version}}_Linux_x64 -m 5 -v"

[windows]
run-mysteries-solutions:
  hyperfine --warmup 3 --export-markdown mysteries.md --show-output --min-runs 10 "release\rust_mystery_{{version}}_Windows_x64.exe -m 1 -v" "release\rust_mystery_{{version}}_Windows_x64.exe -m 2 -v" "release\rust_mystery_{{version}}_Windows_x64.exe -m 3 -v" "release\rust_mystery_{{version}}_Windows_x64.exe -m 4 -v" "release\rust_mystery_{{version}}_Windows_x64.exe -m 5 -v"
